source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


gem 'rails', '~> 5.0.2'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'kaminari'
gem 'jwt'
gem 'bcrypt'
gem 'capistrano'
gem 'rubocop', require: false
# # bundle exec rake doc:rails generates the API under doc/api.
# gem 'sdoc', group: :doc
group :test do
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'rspec-prof', git: 'https://github.com/sinisterchipmunk/rspec-prof.git'
  gem 'codeclimate-test-reporter', require: false
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'faker'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'pry-rails'
  gem 'email_spec'
end

group :development do
  gem 'spring'
  gem 'listen'
end


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
