# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7f8f08889b9a28c12ed3b57a89cab2c9a15d2463ee7c0a19ab4dfd140912d8037e23f9e21c4a2a506f1305f72d0c4a5a92495521215d40d61b479a021b94394

test:
  secret_key_base: 2ba1547b5ade49624f54fdae07bea63c96e0248d015da0fdb3a581b2831e01d454e71f0c790f3bb60ffec451466fa8c1494a5a0e41e1be7da29df32d6f571ba1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
